apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: blood-donation-ingress
  namespace: blood-donation
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - host: blood.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: client
                port:
                  number: 80
          - path: /auth(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: auth
                port:
                  number: 4000
          - path: /donor(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: donor
                port:
                  number: 3000
          - path: /request(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: request
                port:
                  number: 3002
          - path: /appointment(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: appointment
                port:
                  number: 3010